version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7.22
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: daily
      MYSQL_PASSWORD: daily
      MYSQL_DATABASE: daily
      ENV: local
